
* 5/3
Refractored sql-query and improved.
Cleaver query; almost every processing for loca-db done by postgres.
TODO: dedupe roads using postgres. Have draft.


* 3/3
 Parque Natural Ôbo d | W        |  298565114 | en:Obo Natural Park               | en:Obo_Natural_Park
 Parque Natural Ôbo d | R        |    4109839 | en:Obo Natural Park               | en:Obo_Natural_Park

 São Tomé e Príncipe  | R        |     535880 | en:São Tomé and Príncipe          | en:São_Tomé_and_Príncipe
 São Tomé e Príncipe  | N        |  249399429 | fr:Sao Tomé-et-Principe           | fr:Sao_Tomé-et-Principe


* 25/2
Bug i sql-queryn: behöver specificera 'window frame' för partition för att inkludera alla element i partitionen:
window w as (partition by osm_type,osm_id order by place_id *range between unbounded preceding and unbounded following*)


* 11/2
Kommando som avslöjar nominatim's ClassTypes.php: egrep -iv " (\w+?)[ _:].*?'\1.*'" tags-from-classTypes
 -allt av intresse i dokumentet är spec för boundary:administrative.


* 5/2

Nominatim, samma objekt har flera entries i databasen, en per tag

São Tomé e Príncipe:
place_id 102524 ignoreras vid sök på nominatim.openstreetmap.org
place_id 100001 finns

 place_id | parent_place_id | linked_place_id |    importance     | geometry_sector | rank_address | rank_search | partition | indexed_status |  osm_id   | osm_type |  class   |      type      |        left         | admin_level |                address                 |                                                extratags                                                 | country_code | housenumber | postcode |        wikipedia         |                      centroid
----------+-----------------+-----------------+-------------------+-----------------+--------------+-------------+-----------+----------------+-----------+----------+----------+----------------+---------------------+-------------+----------------------------------------+----------------------------------------------------------------------------------------------------------+--------------+-------------+----------+--------------------------+----------------------------------------------------
   100001 |               0 |          102524 | 0.479251282826472 |        53493499 |            4 |           4 |        53 |              0 | 249399429 | N        | place    | country        | São Tomé e Príncipe |          15 | "continent"=>"Africa"                  | "wikidata"=>"Q1039", "wikipedia"=>"fr:Sao Tomé-et-Principe", "population"=>"206178"                      | st           |             |          | fr:Sao_Tomé-et-Principe  | 0101000020E6100000A354675A07DC1B406D4892D6CE66EC3F
   102524 |               0 |                 | 0.545732015393547 |        53493499 |            4 |           4 |        53 |              0 |    535880 | R        | boundary | administrative | São Tomé e Príncipe |           2 | "country"=>"ST", "continent"=>"Africa" | "place"=>"country", "wikidata"=>"Q1039", "wikipedia"=>"en:São Tomé and Príncipe", "population"=>"206178" | st           |             |          | en:São_Tomé_and_Príncipe | 0101000020E6100000A354675A07DC1B406D4892D6CE66EC3F


* 3/2

todo:
- Same wiki-data -> same geo-object (merge)
- Better category than tag-key. e.g https://nominatim.openstreetmap.org/details.php?place_id=198799046. boundary:administrative men när söker: county


* 2019

Tag -> category, tools:

- Special phrases, nominatim: https://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases
- Overpass turbo, source: /data/iD_presets_en.json
- Nominatim method in website search's result listing ?

Ej hårdkådad tag: natural=saddle. tex: Collado Resinero
Ej förekommande i översättningslistor nämnda ovan, tex: mountain_pass
