/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Loca_db_construction;

import org.junit.Test;
import static org.junit.Assert.*;

import java.sql.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());

        System.out.println("Hello!");
    }

    @Test
    public void generalDb() {
        String url = "jdbc:postgresql://localhost/test";

    }
}
